#!/bin/bash
# EC2 Setup Commands - Run these AFTER connecting to EC2
# This is a reference script - copy commands one by one


echo "=========================================="
echo "EC2 BACKEND DEPLOYMENT - QUICK REFERENCE"
echo "=========================================="
echo ""
echo "Step 1: Update system and install software"
echo "-------------------------------------------"
echo "sudo yum update -y"
echo "sudo yum install -y git"
echo "curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -"
echo "sudo yum install -y nodejs"
echo "sudo npm install -g pm2"
echo ""
echo "Step 2: Clone repository from GitHub"
echo "-------------------------------------------"
echo "git clone https://github.com/Jishan010/portfolio.git"
echo "cd portfolio/backend"
echo "npm install --production"
echo ""
echo "Step 3: Start backend with PM2"
echo "-------------------------------------------"
echo "pm2 start server.js --name portfolio-backend"
echo "pm2 status"
echo "pm2 logs portfolio-backend --lines 20"
echo "pm2 startup"
echo "# Run the command PM2 shows, then:"
echo "pm2 save"
echo ""
echo "Step 4: Install and configure Nginx"
echo "-------------------------------------------"
echo "sudo yum install -y nginx"
echo "sudo systemctl start nginx"
echo "sudo systemctl enable nginx"
echo "sudo nano /etc/nginx/conf.d/portfolio.conf"
echo "# Paste the Nginx config from the guide"
echo "sudo nginx -t"
echo "sudo systemctl restart nginx"
echo ""
echo "Step 5: Test your backend"
echo "-------------------------------------------"
echo "curl http://localhost:5000/api/health"
echo "# Or visit: http://YOUR-EC2-IP/api/health"
echo ""
echo "=========================================="
echo "USEFUL COMMANDS FOR LATER"
echo "=========================================="
echo ""
echo "Update backend after GitHub push:"
echo "  cd ~/portfolio && git pull origin main"
echo "  cd backend && npm install --production"
echo "  pm2 restart portfolio-backend"
echo ""
echo "View logs:"
echo "  pm2 logs portfolio-backend"
echo "  pm2 logs portfolio-backend --lines 50"
echo ""
echo "Check status:"
echo "  pm2 status"
echo "  sudo systemctl status nginx"
echo ""
echo "Restart services:"
echo "  pm2 restart portfolio-backend"
echo "  sudo systemctl restart nginx"
echo ""
echo "=========================================="
